## ✅Agenda

### ☑ Introduction to Pandas
### ☑ Diff function Pandas
### ☑ Why Pandas
### ☑ Coding Example

In [9]:
import pandas as pd
import numpy as np

In [10]:
np.__version__

'2.1.3'

In [8]:
pd.__version__

'2.2.3'

In [12]:
nums = [5, 4, 10, 5, 0, 7, 50]

In [11]:
# pd.Series() -- > convert data into series

In [16]:
num_series = pd.Series(nums)
num_series

0     5
1     4
2    10
3     5
4     0
5     7
6    50
dtype: int64

In [15]:
type(num_series)

pandas.core.series.Series

In [20]:
print(num_series.max())
print(num_series.min())
print(num_series.mean())
print(num_series.std())
print(num_series.median())
print(num_series.values)

50
0
11.571428571428571
17.212951934102247
5.0
[ 5  4 10  5  0  7 50]

In [21]:
# combine and create two series

In [44]:
s1 = pd.Series([10, 20, 30], index=['a', 'b', 'c'], name="s1")
s2 = pd.Series([10, 20, 30], index=['d', 'e', 'f'], name="s2")

In [27]:
s1

a    10
b    20
c    30
Name: s1, dtype: int64

In [28]:
s2

d    10
e    20
f    30
Name: s2, dtype: int64

In [33]:
# concat = combine multiple series to form dataframe

pd.concat([s1, s2], axis=1) # combine data columnwise

     s1    s2
a  10.0   NaN
b  20.0   NaN
c  30.0   NaN
d   NaN  10.0
e   NaN  20.0
f   NaN  30.0

In [37]:
T1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'], name="T1")
T2 = pd.Series([4, 5, 6], index=['a', 'b', 'c'], name="T2")

In [40]:
new_df = pd.concat([T1, T2], axis=1)  # axis=1 coloum wise 
new_df

   T1  T2
a   1   4
b   2   5
c   3   6

In [41]:
print(new_df)

   T1  T2
a   1   4
b   2   5
c   3   6

In [46]:
type(pd.concat([T1, T2], axis=0)) # axis=0 row wise

pandas.core.series.Series

In [42]:
type(new_df)

pandas.core.frame.DataFrame

In [ ]:
# data loading

In [49]:
df = pd.read_csv("telecom_churn.csv")

In [53]:
# .head() = display first ten rows from the data

df.head(10)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
5,AL,118,510,Yes,No,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False
6,MA,121,510,No,Yes,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False
7,MO,147,415,Yes,No,0,157.0,79,26.69,103.1,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False
8,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
9,WV,141,415,Yes,Yes,37,258.6,84,43.96,222.0,111,18.87,326.4,97,14.69,11.2,5,3.02,0,False

In [55]:
# .tail() = display last 10 rows from the data

df.tail(10)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3323,IN,117,415,No,No,0,118.4,126,20.13,249.3,97,21.19,227.0,56,10.22,13.6,3,3.67,5,True
3324,WV,159,415,No,No,0,169.8,114,28.87,197.7,105,16.80,193.7,82,8.72,11.6,4,3.13,1,False
3325,OH,78,408,No,No,0,193.4,99,32.88,116.9,88,9.94,243.3,109,10.95,9.3,4,2.51,2,False
3326,OH,96,415,No,No,0,106.6,128,18.12,284.8,87,24.21,178.9,92,8.05,14.9,7,4.02,1,False
3327,SC,79,415,No,No,0,134.7,98,22.90,189.7,68,16.12,221.4,128,9.96,11.8,5,3.19,2,False
3328,AZ,192,415,No,Yes,36,156.2,77,26.55,215.5,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
3329,WV,68,415,No,No,0,231.1,57,39.29,153.4,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
3330,RI,28,510,No,No,0,180.8,109,30.74,288.8,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
3331,CT,184,510,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False
3332,TN,74,415,No,Yes,25,234.4,113,39.85,265.9,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

In [56]:
# .shape = number of rows and columns in data

df.shape

(3333, 20)

In [57]:
# .size = number of data points in data (row*col)

df.size

66660

In [60]:
# .columns = : gives a list of columns present in data

df.columns

Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='object')

In [61]:
df.columns.to_list()

['State',
 'Account length',
 'Area code',
 'International plan',
 'Voice mail plan',
 'Number vmail messages',
 'Total day minutes',
 'Total day calls',
 'Total day charge',
 'Total eve minutes',
 'Total eve calls',
 'Total eve charge',
 'Total night minutes',
 'Total night calls',
 'Total night charge',
 'Total intl minutes',
 'Total intl calls',
 'Total intl charge',
 'Customer service calls',
 'Churn']

In [62]:
# overall information regarding data

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   State                   3333 non-null   object
 1   Account length          3333 non-null   int64
 2   Area code               3333 non-null   int64
 3   International plan      3333 non-null   object
 4   Voice mail plan         3333 non-null   object
 5   Number vmail messages   3333 non-null   int64
 6   Total day minutes       3333 non-null   float64
 7   Total day calls         3333 non-null   int64
 8   Total day charge        3333 non-null   float64
 9   Total eve minutes       3333 non-null   float64
 10  Total eve calls         3333 non-null   int64
 11  Total eve charge        3333 non-null   float64
 12  Total night minutes     3333 non-null   float64
 13  Total night calls       3333 non-null   int64
 14  Total night charge      3333 non-null   float64
 15  Total intl minutes      3333 non-null   float64
 16  Total intl calls        3333 non-null   int64
 17  Total intl charge       3333 non-null   float64
 18  Customer service calls  3333 non-null   int64
 19  Churn                   3333 non-null   bool
dtypes: bool(1), float64(8), int64(8), object(3)
memory usage: 498.1+ KB

In [65]:
# .isnull().sum() : count of all null values in data

df.isnull().sum()

State                     0
Account length            0
Area code                 0
International plan        0
Voice mail plan           0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Customer service calls    0
Churn                     0
dtype: int64

In [67]:
# statistical information

df.describe()

,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls
count,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000
mean,101.064806,437.182418,8.099010,179.775098,100.435644,30.562307,200.980348,100.114311,17.083540,200.872037,100.107711,9.039325,10.237294,4.479448,2.764581,1.562856
std,39.822106,42.371290,13.688365,54.467389,20.069084,9.259435,50.713844,19.922625,4.310668,50.573847,19.568609,2.275873,2.791840,2.461214,0.753773,1.315491
min,1.000000,408.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.200000,33.000000,1.040000,0.000000,0.000000,0.000000,0.000000
25%,74.000000,408.000000,0.000000,143.700000,87.000000,24.430000,166.600000,87.000000,14.160000,167.000000,87.000000,7.520000,8.500000,3.000000,2.300000,1.000000
50%,101.000000,415.000000,0.000000,179.400000,101.000000,30.500000,201.400000,100.000000,17.120000,201.200000,100.000000,9.050000,10.300000,4.000000,2.780000,1.000000
75%,127.000000,510.000000,20.000000,216.400000,114.000000,36.790000,235.300000,114.000000,20.000000,235.300000,113.000000,10.590000,12.100000,6.000000,3.270000,2.000000
max,243.000000,510.000000,51.000000,350.800000,165.000000,59.640000,363.700000,170.000000,30.910000,395.000000,175.000000,17.770000,20.000000,20.000000,5.400000,9.000000

In [70]:
df.describe(include='O') # O = object

       State International plan Voice mail plan
count   3333               3333            3333
unique    51                  2               2
top       WV                 No              No
freq     106               3010            2411

In [71]:
df.describe(include='all')

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
count,3333,3333.000000,3333.000000,3333,3333,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333
unique,51,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
top,WV,NaN,NaN,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
freq,106,NaN,NaN,3010,2411,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2850
mean,NaN,101.064806,437.182418,NaN,NaN,8.099010,179.775098,100.435644,30.562307,200.980348,100.114311,17.083540,200.872037,100.107711,9.039325,10.237294,4.479448,2.764581,1.562856,NaN
std,NaN,39.822106,42.371290,NaN,NaN,13.688365,54.467389,20.069084,9.259435,50.713844,19.922625,4.310668,50.573847,19.568609,2.275873,2.791840,2.461214,0.753773,1.315491,NaN
min,NaN,1.000000,408.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.200000,33.000000,1.040000,0.000000,0.000000,0.000000,0.000000,NaN
25%,NaN,74.000000,408.000000,NaN,NaN,0.000000,143.700000,87.000000,24.430000,166.600000,87.000000,14.160000,167.000000,87.000000,7.520000,8.500000,3.000000,2.300000,1.000000,NaN
50%,NaN,101.000000,415.000000,NaN,NaN,0.000000,179.400000,101.000000,30.500000,201.400000,100.000000,17.120000,201.200000,100.000000,9.050000,10.300000,4.000000,2.780000,1.000000,NaN
75%,NaN,127.000000,510.000000,NaN,NaN,20.000000,216.400000,114.000000,36.790000,235.300000,114.000000,20.000000,235.300000,113.000000,10.590000,12.100000,6.000000,3.270000,2.000000,NaN
max,NaN,243.000000,510.000000,NaN,NaN,51.000000,350.800000,165.000000,59.640000,363.700000,170.000000,30.910000,395.000000,175.000000,17.770000,20.000000,20.000000,5.400000,9.000000,NaN

In [72]:
# methods to access column (one)

In [86]:
# method 1 : using square brackets [ ]

df['State']

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: object

In [88]:
# method 2 : using dot (.)

df.Churn

0       False
1       False
2       False
3       False
4       False
        ...
3328    False
3329    False
3330    False
3331    False
3332    False
Name: Churn, Length: 3333, dtype: bool

In [89]:
# problem with method 2 --> space is not allowed while accecing the object

df.Area code #

SyntaxError: invalid syntax (1530367887.py, line 1)

In [90]:
df.columns

Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='object')

In [111]:
# access multiple columns : [[ column name ]]

df[['Total eve calls', 'Total eve charge', 'Total night minutes', ]]

      Total eve calls  Total eve charge  Total night minutes
0                  99             16.78                244.7
1                 103             16.62                254.4
2                 110             10.30                162.6
3                  88              5.26                196.9
4                 122             12.61                186.9
...               ...               ...                  ...
3328              126             18.32                279.1
3329               55             13.04                191.3
3330               58             24.55                191.9
3331               84             13.57                139.2
3332               82             22.60                241.4

[3333 rows x 3 columns]

In [97]:
# subset dataframe using iloc : iloc[n1:n2,m1:m2], i = index, loc = location
# n1,n2 = rows
# m1,m2 = columns

In [104]:
df.iloc[0:10]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
5,AL,118,510,Yes,No,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False
6,MA,121,510,No,Yes,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False
7,MO,147,415,Yes,No,0,157.0,79,26.69,103.1,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False
8,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
9,WV,141,415,Yes,Yes,37,258.6,84,43.96,222.0,111,18.87,326.4,97,14.69,11.2,5,3.02,0,False

In [112]:
df.iloc[0:10, 5:10]

,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes
0,25,265.1,110,45.07,197.4
1,26,161.6,123,27.47,195.5
2,0,243.4,114,41.38,121.2
3,0,299.4,71,50.90,61.9
4,0,166.7,113,28.34,148.3
5,0,223.4,98,37.98,220.6
6,24,218.2,88,37.09,348.5
7,0,157.0,79,26.69,103.1
8,0,184.5,97,31.37,351.6
9,37,258.6,84,43.96,222.0

In [113]:
df.columns

Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='object')

In [115]:
# subsetting data based on column names
#.loc = provide row index and column mames

In [116]:
df.loc[0:10, ['Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn']]

    Total intl calls  Total intl charge  Customer service calls  Churn
0                  3               2.70                       1  False
1                  3               3.70                       1  False
2                  5               3.29                       0  False
3                  7               1.78                       2  False
4                  3               2.73                       3  False
5                  6               1.70                       0  False
6                  7               2.03                       3  False
7                  6               1.92                       0  False
8                  4               2.35                       1  False
9                  5               3.02                       0  False
10                 6               3.43                       4   True

In [121]:
df.iloc[0:5]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [119]:
df.loc[0:5]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
5,AL,118,510,Yes,No,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False

In [126]:
# value_counts : count of each category present in that column

df.value_counts('State').iloc[0:10]

State
WV    106
MN     84
NY     83
AL     80
OH     78
WI     78
OR     78
WY     77
VA     77
CT     74
Name: count, dtype: int64

In [129]:
# value_counts : count of each category present in that column

df['State'].value_counts().iloc[0:10]

State
WV    106
MN     84
NY     83
AL     80
OH     78
WI     78
OR     78
WY     77
VA     77
CT     74
Name: count, dtype: int64

In [128]:
df.value_counts('Churn')

Churn
False    2850
True      483
Name: count, dtype: int64

In [130]:
df['Churn'].value_counts()

Churn
False    2850
True      483
Name: count, dtype: int64

In [131]:
df['Churn'].value_counts(normalize=True)

Churn
False    0.855086
True     0.144914
Name: proportion, dtype: float64

In [132]:
df['Churn'].value_counts(normalize=True)*100

Churn
False    85.508551
True     14.491449
Name: proportion, dtype: float64

In [138]:
df['State'].value_counts(normalize=True).iloc[0:10]*100

State
WV    3.180318
MN    2.520252
NY    2.490249
AL    2.400240
OH    2.340234
WI    2.340234
OR    2.340234
WY    2.310231
VA    2.310231
CT    2.220222
Name: proportion, dtype: float64

In [149]:
# sort

df.sort_values(by = 'State')

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
181,AK,126,415,No,No,0,58.2,94,9.89,138.7,118,11.79,136.8,91,6.16,11.9,1,3.21,5,True
550,AK,111,415,No,No,0,172.8,58,29.38,183.1,108,15.56,158.8,104,7.15,7.9,3,2.13,4,True
2929,AK,71,510,No,No,0,185.0,84,31.45,232.5,129,19.76,191.1,82,8.60,14.9,4,4.02,3,False
1260,AK,76,415,No,Yes,22,160.1,107,27.22,168.7,136,14.34,23.2,102,1.04,9.5,4,2.57,3,False
1803,AK,101,510,No,No,0,174.9,105,29.73,262.0,75,22.27,210.0,93,9.45,8.5,5,2.30,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3258,WY,148,408,No,No,0,243.0,115,41.31,191.8,91,16.30,117.8,93,5.30,13.4,5,3.62,2,False
1265,WY,95,415,No,Yes,39,260.8,130,44.34,213.4,111,18.14,195.6,97,8.80,10.1,5,2.73,1,False
762,WY,161,415,Yes,No,0,189.6,78,32.23,267.4,117,22.73,184.5,137,8.30,1.3,6,0.35,1,False
1628,WY,131,510,No,No,0,110.9,74,18.85,115.6,90,9.83,190.5,114,8.57,15.8,9,4.27,1,False
609,WY,111,415,No,No,0,146.2,55,24.85,261.5,83,22.23,163.2,116,7.34,8.7,3,2.35,3,False

In [154]:
df_sorted = df.sort_values(by = ['State', 'Account length'], ascending=False)
df_sorted

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
1751,WY,225,415,No,No,0,182.7,142,31.06,246.5,63,20.95,218.0,103,9.81,8.8,2,2.38,1,False
238,WY,215,510,No,No,0,83.6,148,14.21,120.9,91,10.28,226.6,110,10.20,10.7,9,2.89,0,False
1064,WY,185,415,Yes,Yes,30,154.1,114,26.20,118.7,106,10.09,258.4,105,11.63,12.9,3,3.48,2,False
2439,WY,177,415,No,No,0,175.7,120,29.87,168.6,90,14.33,198.9,110,8.95,14.6,4,3.94,1,False
668,WY,171,415,No,No,0,231.2,135,39.30,188.7,74,16.04,206.9,124,9.31,12.3,1,3.32,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1054,AK,50,408,No,No,0,183.6,107,31.21,58.6,118,4.98,202.6,99,9.12,8.7,3,2.35,1,False
282,AK,48,415,No,Yes,37,211.7,115,35.99,159.9,84,13.59,144.1,80,6.48,12.2,1,3.29,1,False
505,AK,41,415,No,No,0,159.3,66,27.08,125.9,75,10.70,261.9,76,11.79,11.1,5,3.00,1,False
36,AK,36,408,No,Yes,30,146.3,128,24.87,162.5,80,13.81,129.3,109,5.82,14.5,6,3.92,0,False
2475,AK,1,408,No,No,0,175.2,74,29.78,151.7,79,12.89,230.5,109,10.37,5.3,3,1.43,1,False

In [166]:
df_sorted

,level_0,index,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,...,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,0,1751,WY,225,415,No,No,0,182.7,142,...,63,20.95,218.0,103,9.81,8.8,2,2.38,1,False
1,1,238,WY,215,510,No,No,0,83.6,148,...,91,10.28,226.6,110,10.20,10.7,9,2.89,0,False
2,2,1064,WY,185,415,Yes,Yes,30,154.1,114,...,106,10.09,258.4,105,11.63,12.9,3,3.48,2,False
3,3,2439,WY,177,415,No,No,0,175.7,120,...,90,14.33,198.9,110,8.95,14.6,4,3.94,1,False
4,4,668,WY,171,415,No,No,0,231.2,135,...,74,16.04,206.9,124,9.31,12.3,1,3.32,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,3328,1054,AK,50,408,No,No,0,183.6,107,...,118,4.98,202.6,99,9.12,8.7,3,2.35,1,False
3329,3329,282,AK,48,415,No,Yes,37,211.7,115,...,84,13.59,144.1,80,6.48,12.2,1,3.29,1,False
3330,3330,505,AK,41,415,No,No,0,159.3,66,...,75,10.70,261.9,76,11.79,11.1,5,3.00,1,False
3331,3331,36,AK,36,408,No,Yes,30,146.3,128,...,80,13.81,129.3,109,5.82,14.5,6,3.92,0,False
3332,3332,2475,AK,1,408,No,No,0,175.2,74,...,79,12.89,230.5,109,10.37,5.3,3,1.43,1,False

In [167]:
# .drop = will delete single or multiple columns

df_sorted.drop(['level_0'], inplace=True, axis = 1)

In [168]:
df_sorted

,index,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,1751,WY,225,415,No,No,0,182.7,142,31.06,...,63,20.95,218.0,103,9.81,8.8,2,2.38,1,False
1,238,WY,215,510,No,No,0,83.6,148,14.21,...,91,10.28,226.6,110,10.20,10.7,9,2.89,0,False
2,1064,WY,185,415,Yes,Yes,30,154.1,114,26.20,...,106,10.09,258.4,105,11.63,12.9,3,3.48,2,False
3,2439,WY,177,415,No,No,0,175.7,120,29.87,...,90,14.33,198.9,110,8.95,14.6,4,3.94,1,False
4,668,WY,171,415,No,No,0,231.2,135,39.30,...,74,16.04,206.9,124,9.31,12.3,1,3.32,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,1054,AK,50,408,No,No,0,183.6,107,31.21,...,118,4.98,202.6,99,9.12,8.7,3,2.35,1,False
3329,282,AK,48,415,No,Yes,37,211.7,115,35.99,...,84,13.59,144.1,80,6.48,12.2,1,3.29,1,False
3330,505,AK,41,415,No,No,0,159.3,66,27.08,...,75,10.70,261.9,76,11.79,11.1,5,3.00,1,False
3331,36,AK,36,408,No,Yes,30,146.3,128,24.87,...,80,13.81,129.3,109,5.82,14.5,6,3.92,0,False
3332,2475,AK,1,408,No,No,0,175.2,74,29.78,...,79,12.89,230.5,109,10.37,5.3,3,1.43,1,False

In [171]:
df_sorted.drop(['index'], inplace=True, axis=1)

In [172]:
df_sorted

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,WY,225,415,No,No,0,182.7,142,31.06,246.5,63,20.95,218.0,103,9.81,8.8,2,2.38,1,False
1,WY,215,510,No,No,0,83.6,148,14.21,120.9,91,10.28,226.6,110,10.20,10.7,9,2.89,0,False
2,WY,185,415,Yes,Yes,30,154.1,114,26.20,118.7,106,10.09,258.4,105,11.63,12.9,3,3.48,2,False
3,WY,177,415,No,No,0,175.7,120,29.87,168.6,90,14.33,198.9,110,8.95,14.6,4,3.94,1,False
4,WY,171,415,No,No,0,231.2,135,39.30,188.7,74,16.04,206.9,124,9.31,12.3,1,3.32,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AK,50,408,No,No,0,183.6,107,31.21,58.6,118,4.98,202.6,99,9.12,8.7,3,2.35,1,False
3329,AK,48,415,No,Yes,37,211.7,115,35.99,159.9,84,13.59,144.1,80,6.48,12.2,1,3.29,1,False
3330,AK,41,415,No,No,0,159.3,66,27.08,125.9,75,10.70,261.9,76,11.79,11.1,5,3.00,1,False
3331,AK,36,408,No,Yes,30,146.3,128,24.87,162.5,80,13.81,129.3,109,5.82,14.5,6,3.92,0,False
3332,AK,1,408,No,No,0,175.2,74,29.78,151.7,79,12.89,230.5,109,10.37,5.3,3,1.43,1,False

In [176]:
# no of unique values

df['State'].nunique()

51

In [177]:
df['State'].unique()

array(['KS', 'OH', 'NJ', 'OK', 'AL', 'MA', 'MO', 'LA', 'WV', 'IN', 'RI',
       'IA', 'MT', 'NY', 'ID', 'VT', 'VA', 'TX', 'FL', 'CO', 'AZ', 'SC',
       'NE', 'WY', 'HI', 'IL', 'NH', 'GA', 'AK', 'MD', 'AR', 'WI', 'OR',
       'MI', 'DE', 'UT', 'CA', 'MN', 'SD', 'NC', 'WA', 'NM', 'NV', 'DC',
       'KY', 'ME', 'MS', 'TN', 'PA', 'CT', 'ND'], dtype=object)

In [182]:
df['Area code'].unique()

array([415, 408, 510])

In [183]:
df['New Area code'] = df['Area code'].apply(lambda x : x+100)

In [186]:
df[['Area code','New Area code']]

In [ ]:
# to save the new changes.

df[['Area code','New Area code']].to_csv("Newarecode.csv")